api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    collection:
        pagination:
            page_parameter_name: _page

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
